---

# - set_fact: package_name=httpd
#  when: ansible_os_family == "RedHat"

# - set_fact: package_name=apache2
#  when: ansible_os_family == "Debian"



- hosts: amazon
  remote_user: ec2-user
  tasks:
       - name: Install httpd package
         yum: name=httpd state=latest
         sudo: yes
         when: ansible_os_family == "RedHat"

       - name: Starting httpd service
         service: name=httpd state=started
         sudo: yes
         when: ansible_os_family == "RedHat"


