---
- hosts: aws
  tasks:
       - name: List files in /tmp and redirect to a file
         shell: /bin/ls -l /etc > /tmp/list
         sudo: yes
       
       - name: Cat /tmp/list
         shell: /bin/cat /tmp/list
  
